from pyparsing import *

LBRCKT = Literal('[').suppress()
RBRCKT = Literal(']').suppress()
EQUAL = Literal('=').suppress()
HASH = oneOf('# ;').suppress()
API = Keyword('api').suppress()
CORE = Keyword('core').suppress()
PROJECTS = Keyword('projects').suppress()
VERSION = Keyword('version').suppress()
TYPE = Keyword('type').suppress()
PATCH = Keyword('patch').suppress()
URL = Keyword('url').suppress()
MD5 = Keyword('md5').suppress()
SUBDIR = Keyword('subdir').suppress()
OVERWRITE = Keyword('overwrite').suppress()
TRUTH = oneOf('TRUE FALSE')
DOWNLOAD = Keyword('download').suppress()
BRANCH = Keyword('branch').suppress()
TAG = Keyword('tag').suppress()
REVISION = Keyword('revision').suppress()
LIBRARIES = Keyword('libraries').suppress()
DESTINATION = Keyword('destination').suppress()
DIRECTORYNAME = Keyword('directory_name').suppress()
